services:
  - name: libretranslate
    env:
      - key: LT_LANG_MODEL
        value: "transformer.wmt19.en-de"
    buildCommand: "docker build -t libretranslate-image ."
    startCommand: "docker run -p 5000:5000 libretranslate-image"
    healthCheckPath: "/"
    healthCheckPort: 5000
