services:
  - name: libretranslate
    env:
      - key: LT_LANG_MODEL
        value: "transformer.wmt19.en-de"
      - key: PORT
        value: 5000
    buildCommand: "docker build -t libretranslate ."
    startCommand: "docker run -p 5000:5000 libretranslate"
    healthCheckPath: "/"
    healthCheckPort: 5000
